@startuml

left to right direction
skinparam classAttributeIconSize 0

class Menu
{
    Opret Bil-journal
    Ændre bil-Status
    Tilføj Kunde
    Lejekontrakt
}
Menu "1" --- "1" Opretbiljournal
Menu "1" -- "1" ÆndreStatus
Menu "1" -- "1" TilføjKunde
Menu "1" -- "1" lblalb

class Opretbiljournal 
{
    Kategori
    Navn
    Mærke
    Målgruppe
    +Status
    {method} OpretBiljournal()
}

class ÆndreStatus
{
    Tilgængelig
}

class TilføjKunde
{
    Navn
    Tlf
    Mail
    Køretøj

}

class Lejekontrakt
{
    Navn
    Tlf
    Mail
    Køretøj
    Print
}


@enduml