@startuml
left to right direction

actor Chefen as c
actor Kundeservice as k

package Biludlejning {
usecase "Opret Biljournal" as US1
usecase "registrer Køretøjstatus" as US2
usecase "Registrer Kunde" as US3
usecase "Underskriv Lejekontrakt" as US4 
}
  

c --> US1
c --> US2
k --> US3
k --> US4


@enduml
