@startuml
hide circle
hide empty members
skinparam PackageStyle rectangle

package "Infastructure"
{
    class KeyPartnerships
    {
        
    }

    class KeyActivities
    {
    
    }

    class KeyResources
    {
    }
}

package "CustomerFrontend"
{
    class CustomerRelationships
    {

    }
    class Channels
    {

    }
    class CustomerSegments
    {
    }
}

package "Value"
{
    class ValueProposition
    {

    }
}

package "ProfitFormular"
{
    class CostStructure
    {
    }
    class RevenueStreams
    {
    }
}

Infastructure -[hidden]right-> Value
ProfitFormular -[hidden]up-> Value
Value -[hidden]right-> CustomerFrontend

@enduml