@startuml
left to right direction

'Aktører
actor Medarbejder as m
actor Ledelse as l

'Projekt navn >
package LærerVikaren { 

'Use cases
usecase "Send Lærervikar" as US1
usecase "Registrer Ledighed" as US2
usecase "Slet Lærervikar" as US3
}

'Pile
m --> US1
m --> US2
l --> US3



@enduml