@startuml
hide circle
hide method
left to right direction


Vikar "1..*" -- "0..*" Kalender
Skole "1..*" -- "1..*" Vikar
Vikar "1..*" -- "0..*" Arbejdstid
Vikar "0..*" -- "1..*" Ledelse_Gunbritt
Skole "0..*" -- "1..*" Ledelse_Gunbritt


Class Vikar 
{
    navn
    tlf
    cpr
    alder
    fag
}


Class Kalender 
{
    tilrådighed
    arbejdstid
    dato
    fag
}

Class Arbejdstid
{
    timer
}


Class Skole
{
    Navn
    Adresse
    By
    Email
    Tlf
}
Class Ledelse_Gunbritt
{
    Navn
    Email
    Tlf
}




@enduml
