@startuml
left to right direction

'Aktører
actor Medarbejder as m

'Projekt navn >
package LærerVikaren { 

'Use cases
usecase "Send Lærervikar" as US1
usecase "Registrer Ledighed" as US2
}

'Pile
m --> US1
m --> US2



@enduml