@startuml
hide circle
hide empty members





SUBSTITUTE_MANAGMENT_GUNBRITT "1..*" -- "1..*" Management_Gunbritt
SUBSTITUTE_MANAGMENT_GUNBRITT "1..*" -- "1..*" Substitute


Class Substitute <<table>>
{
   <<PK>> <<surrogate>> SubstituteID : int
    Name : NVarChar(255)
    Phone : NVarChar(255)
    Subject : NVarChar(255)
    Cpr : int
    Age : int
    
    <<PK>> PK_Substitute()
}

' Class Calendar <<table>>
' {

'     Avalibility : Bit
'     WorkingHours : Float
'     Date : DateTime2
'     Subject : NVarChar(255)
    

' }

' Class School <<table>>
' {
'     Name : NVarChar(255)
'     Address : NVarChar(255)
'     City :  NVarChar(255)
'     Email : NVarChar(255)
'     Phone : NVarChar(255)
' }

Class Management_Gunbritt <<table>>
{
    <<PK>> <<surrogate>> ManagementID : int
    Name : NVarChar(255)
    Email : NVarChar(255)
    Phone : NVarChar(255)
    --
    <<PK>> PK_Management()
}
CLass SUBSTITUTE_MANAGMENT_GUNBRITT <<table>>
{
    <<PK>> <<FK1>> SubstituteID : int
    <<PK>> <<FK2>> ManagementID : int
    --
    <<PK>> PK_SubstituteManagement()
    <<FK1>> FK_SubstituteManagement_Substitute(SubstituteID)
    <<FK2>> FK_SubstituteManagement_Management(ManagementID)
}

@enduml