@startuml
hide circle



Dashboard "1" -- "1" Admin
Dashboard "1" -- "1" Co2Udledning
Dashboard "1" -- "1" Affald
Dashboard "1" -- "1" Energiforbrug
Dashboard "1" -- "0..*" Bremsekaliber
Co2Udledning "1..*" -- "0..*" Bremsekaliber
Affald "1..*" -- "0..*" Bremsekaliber
Energiforbrug "1..*" -- "0..*" Bremsekaliber


Class Bremsekaliber
{
    id
    vægt
    råmateriale
    komponenter
}

Class Admin
{
    id
    navn
}


Class Dashboard
{
    bæredygtighedsdata
    graf
}

Class Co2Udledning 
{
    graf
    udledning
}

Class Affald
{
    graf
    vægt
    råmateriale
}

Class Energiforbrug
{
    graf
    watt
}



@enduml