@startuml
hide circle
skinparam classAttributeIconSize 0

Co2Discharge "1..*" -- "1" BrakeCaliber
Waste "1..*" -- "1" BrakeCaliber
EnergyUse "1..*" -- "1" BrakeCaliber
Inspection "1" -- "1..*" Co2Discharge
Inspection "1" -- "1..*" Waste
Inspection "1" -- "1..*" EnergyUse

Class BrakeCaliber
{
    +Weight : double
    +RawMaterial : string
    +Component : string
    __
    
}

Class Co2Discharge 
{
    +Discharge : double
}

Class Waste
{
    +WasteAmount : double
    +Material : string
}

Class EnergyUse
{
    +Watt : double
}

Class Inspection
{
    +Date : DateTime
    +Milestone : double
    +MilestoneReached: bool
    +Inspector : string
}

Class BrakeCaliberRepo
{
    -bc : BrakeCaliber
    __
    +bcAdd(brakeCaliber : Brakecaliber)
    +bcGetAll() : List<BrakeCaliber>
    +bcRemove(brakeCaliber : Brakecaliber)   
    +bcGetById(id: int) : BrakeCaliber
}

Class InspectionRepo
{ 
    -inspection : Inspection
    __
    +inspecAdd(inspec : Inspection)
    +inspecGetAll() : List<Inspection>
    +inspecRemove(inspection : Inspection)
    +InspecGetById(id : int) : Inspection
}


Class Co2Repo
{
    -co2Discharge : Co2Discharge
    __
    +Co2Add(co2 : Co2Discharge)
    +Co2GetAll() : List<Co2Discharge>
    +Co2Remove(co2 : Co2Discharge)
    +Co2GetById(id : int) : Co2Discharge
}

Class WasteRepo
{
    -waste : Waste
    __
    +WasteAdd(waste : Waste)
    +WasteGetAll() : List<Waste>
    +WasteRemove(waste : Waste)
    +WasteGetById(id : int) : Waste
}

Class EnergyRepo
{
    -energyUse : EnergyUse
    __
    +EnergyAdd(energy : EnergyUse)
    +EnergyGetAll() : List<EnergyUse>
    +EnergyRemove(energy : EnergyUse)
    +EnergyGetById(id : int) : Energyuse
}




Class Controller
{

}

@enduml