@startuml
hide circle
hide empty members

Co2Udledning "1..*" -- "0..*" Bremsekaliber
Affald "1..*" -- "0..*" Bremsekaliber
Energiforbrug "1..*" -- "0..*" Bremsekaliber

Class Bremsekaliber
{
    vægt
    råmateriale
    komponenter
}

Class Co2Udledning 
{
    udledning
}

Class Affald
{
    vægt
    råmateriale
}

Class Energiforbrug
{
    watt
}


@enduml