@startuml
hide circles
skinparam ClassAttributeIconSize 0
skinparam PackageBorderStyle dashed

Package ApplicationLayer
{
    
Class PetRepository
{
    pets : List<Pet>
    ..
    + Create(pet : Pet)
    + Update(pet : Pet)
    + Delete(pet : Pet)
}

Class OwnerRepository
{
    owners : List<Owner>
    ..
    + Create(owner : Owner)
    + Update(owner : Owner)
    + Delete(owner : Owner)
}

Class Controller <<controller>>
{
    -  _ownerRepository : OwnerRepository
    - _petRepository : PetRepository
    ..
    + PetAdd(pet : Pet)
    + PetDelete(pet : Pet)
    + OwnerAdd(owner : Owner) 
    + OwnerDelete(owner : Owner)
    + GetAll ()
}
}

Package DomainLayer
{
    class Pet
{
    name : string 
    type : string 
    breed : string 
    dateofbirth : DateOnly
    weight : double
    
}

class Owner
{
    lastname : string 
    firstname : string 
    phone : string
    email : string 
}

Class Service
{
    type : string 
    date : DateTime
}

Class Charge 
{
    amount : double 
}

}

Owner --> Pet
Pet --> Service
Charge  <-- Owner
Controller -down-> PetRepository
Controller -up-> OwnerRepository
OwnerRepository --> Owner
PetRepository --> Pet

ApplicationLayer -up[hidden]-  DomainLayer

@enduml